name: Notify Parent Repository pavimentos-img
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Parent Repository pavimentos-img Update
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}  # Changed to PAT
          repository: jthebest/pavimentos
          event-type: submodule-updated
          client-payload: |
            {
              "submodule": "pavimentos-img",
              "ref": "${{ github.ref }}",
              "sha": "${{ github.sha }}",
              "message": "${{ github.event.head_commit.message }}",
              "timestamp": "${{ github.event.head_commit.timestamp }}"
            }